name: CI/CD Pipeline for Client and Server

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  client:
   name: AI-Assistant_client
   runs-on: ubuntu-latest
   steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Navigate to Client Folder
      working-directory: ./AI-Assistant-Client
      run: echo "Inside Client Directory"

    - name: Install Client Dependencies
      working-directory: ./AI-Assistant-Client
      run: npm install

    - name: Lint Client Code
      working-directory: ./AI-Assistant-Client
      run: npm run lint

    - name: Run Client Unit Tests
      working-directory: ./AI-Assistant-Client
      run: npm test

    - name: Build Client
      working-directory: ./AI-Assistant-Client
      run: npm run build

    - name: Install Netlify
      working-directory: ./AI-Assistant-Client
      run: npm install netlify-cli@17.10.1 -g

    - name: Deploy Client to Netlify
      id: netlify_deploy
      working-directory: ./AI-Assistant-Client
      run: |
        netlify deploy \
          --dir dist \
          --site ${{ secrets.NETLIFY_SITE_ID }} \
          --auth ${{ secrets.NETLIFY_AUTH_TOKEN }} \
          --prod

  server:
    name: AI-Assistant_server
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3

    - name: Navigate to Server Folder
      working-directory: ./AI-Assistant-Server
      run: echo "Inside Server Directory"

    - name: Install Server Dependencies
      working-directory: ./AI-Assistant-Server
      run: npm install

    - name: Deploy to render
      working-directory: ./AI-Assistant-Server
      run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{"serviceId": "${{ secrets.RENDER_SERVICE_ID }}"}' \
            https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploy
        